image: Visual Studio 2015

environment:
  path: build\__install__\bin\;%PATH%

configuration:
  - Release

cache:
  - build

install:
  - cmd: C:\Python36-x64\python.exe scripts\python\build.py --path build --boost_path C:\Libraries\boost_1_63_0 --qt_path C:\Qt\5.9.1\msvc2015_64 --colmap_update --colmap_branch %APPVEYOR_REPO_BRANCH% --build_type %CONFIGURATION%

build:
  project: build\colmap-%APPVEYOR_REPO_BRANCH%\build\RUN_TESTS.vcxproj
