language: cpp
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - build-essential
      - libboost-program-options-dev
      - libboost-filesystem-dev
      - libboost-graph-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-test-dev
      - libeigen3-dev
      - libatlas-base-dev
      - libsuitesparse-dev
      - libfreeimage-dev
      - libgoogle-glog-dev
      - libgflags-dev
      - libglew-dev
      - libcgal-dev
      - nvidia-profiler
      - nvidia-cuda-dev
      - nvidia-cuda-toolkit

matrix:
  include:
    - os: linux
      env:
        - PATH="/opt/qt54/bin:$PATH"
        - CMAKE_OPTIONS="-DOPENGL_ENABLED=OFF -DCUDA_ENABLED=OFF -DCGAL_ENABLED=ON -DTESTS_ENABLED=ON -DCeres_DIR=${TRAVIS_BUILD_DIR}/deps/ceres-solver/install/lib/cmake/Ceres"
        - QT_QPA_PLATFORM="offscreen"
        - QT_VERSION=qt596
    - os: linux
      env:
        - PATH="/opt/qt54/bin:$PATH"
        - CMAKE_OPTIONS="-DOPENGL_ENABLED=OFF -DCUDA_ENABLED=OFF -DCGAL_ENABLED=ON -DTESTS_ENABLED=OFF -DCeres_DIR=${TRAVIS_BUILD_DIR}/deps/ceres-solver/install/lib/cmake/Ceres"
        - QT_QPA_PLATFORM="offscreen"
        - QT_VERSION=542
    - os: linux
      env:
        - PATH="/opt/qt54/bin:$PATH"
        - CMAKE_OPTIONS="-DOPENGL_ENABLED=OFF -DCUDA_ENABLED=OFF -DCGAL_ENABLED=OFF -DTESTS_ENABLED=ON -DCeres_DIR=${TRAVIS_BUILD_DIR}/deps/ceres-solver/install/lib/cmake/Ceres"
        - QT_QPA_PLATFORM="offscreen"
        - QT_VERSION=qt596
    - os: linux
      env:
        - PATH="/opt/qt54/bin:$PATH"
        - CMAKE_OPTIONS="-DOPENGL_ENABLED=ON -DCUDA_ENABLED=ON -DCGAL_ENABLED=ON -DTESTS_ENABLED=OFF -DCeres_DIR=${TRAVIS_BUILD_DIR}/deps/ceres-solver/install/lib/cmake/Ceres"
        - QT_QPA_PLATFORM="offscreen"
        - QT_VERSION=qt596
    - os: linux
      env:
        - PATH="/opt/qt54/bin:$PATH"
        - CMAKE_OPTIONS="-DOPENGL_ENABLED=OFF -DCUDA_ENABLED=ON -DCGAL_ENABLED=ON -DTESTS_ENABLED=OFF -DCeres_DIR=${TRAVIS_BUILD_DIR}/deps/ceres-solver/install/lib/cmake/Ceres"
        - QT_QPA_PLATFORM="offscreen"
        - QT_VERSION=qt596
    - os: linux
      env:
        - PATH="/opt/qt54/bin:$PATH"
        - CMAKE_OPTIONS="-DOPENGL_ENABLED=ON -DCUDA_ENABLED=OFF -DCGAL_ENABLED=ON -DTESTS_ENABLED=OFF -DCeres_DIR=${TRAVIS_BUILD_DIR}/deps/ceres-solver/install/lib/cmake/Ceres"
        - QT_QPA_PLATFORM="offscreen"
        - QT_VERSION=qt596
    - os: osx
      env:
        - CMAKE_OPTIONS="-DIPO_ENABLED=OFF -DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5"

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps
    - ${TRAVIS_BUILD_DIR}/build

before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew tap homebrew/science
      brew install \
        cmake \
        boost \
        eigen \
        freeimage \
        glog \
        gflags \
        suite-sparse \
        ceres-solver \
        qt5 \
        glew || true
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3

      sudo add-apt-repository --yes ppa:beineri/opt-qt542-trusty
      sudo apt-get update -qq
      sudo apt-get -y install qt54base

      cd ${TRAVIS_BUILD_DIR}/deps
      if [[ -z "$(ls -A ceres-solver)" ]]; then
        git clone https://ceres-solver.googlesource.com/ceres-solver
      fi
      cd ceres-solver
      git pull
      mkdir -p build
      cd build
      cmake .. \
        -DBUILD_TESTING=OFF \
        -DBUILD_EXAMPLES=OFF
      make -j2
      sudo make install
      cd ${TRAVIS_BUILD_DIR}
    fi

script:
  - cmake --version
  - cd build
  - |
    if [[ -z "$(ls -A colmap)" ]]; then
      git clone https://github.com/colmap/colmap.git
    fi
  - cd colmap
  - git pull
  - git checkout ${TRAVIS_BRANCH}
  - mkdir -p build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release ${CMAKE_OPTIONS}
  - make -j2
  - CTEST_OUTPUT_ON_FAILURE=1 make test
